import { sql, type SQL } from "drizzle-orm";
import {
  check,
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
  type AnySQLiteColumn,
} from "drizzle-orm/sqlite-core";

/**
 * Sideout schema (spec §6). Conventions that keep the SQLite build a driver
 * swap away from Postgres:
 *
 * - ids are UUID v7 strings (`text`), minted in application code (`@/lib/uuid`)
 * - timestamps are integer epoch milliseconds, UTC
 * - money is integer cents with an explicit `currency` column, never a float
 * - enums are text columns with a CHECK constraint, generated by `enumColumn`;
 *   Postgres accepts the same `col IN (...)` check verbatim
 * - booleans are `integer` in boolean mode (0/1), `boolean` in Postgres
 * - no SQLite-only types, no JSON column type; JSON payloads are `text`
 *
 * The two ledgers — `donations` (charitable entry fees) and `rewards`/`sponsors`
 * (prize side) — share no foreign key (spec §4.3).
 */

// ---------------------------------------------------------------------------
// Enum vocabularies. Exported so domain code and zod schemas share one source.
// ---------------------------------------------------------------------------

export const VERIFICATION_STATES = [
  "unverified",
  "verified",
  "not_allowed",
  "demographics_missing",
] as const;
/**
 * `forming` and `disbanded` are not in spec §6.1. `forming` is the state between
 * `POST /api/teams` (captain plus a pending partner invite) and
 * `POST /api/tournaments/:slug/register` (both members in, donation intent
 * created); `disbanded` is a forming team its captain or partner abandoned by
 * creating or joining another before it registered. Neither counts toward
 * capacity or appears on a public roster; `withdrawn` stays reserved for a team
 * that had registered. Recorded as a deviation in docs/open-questions.md.
 */
export const TEAM_STATUSES = ["forming", "registered", "checked_in", "withdrawn", "disbanded"] as const;
export const USER_ROLES = ["player", "organizer"] as const;
export const TEAM_INVITE_STATUSES = ["pending", "accepted", "revoked"] as const;
export const TEAM_ROLES = ["captain", "player"] as const;
export const TOURNAMENT_FORMATS = ["pool_to_bracket", "single_elim", "double_elim", "round_robin"] as const;
export const DIVISIONS = ["open", "womens", "mens", "coed", "rec"] as const;
export const PRIZE_KINDS = ["free_to_play_rewards", "real_money"] as const;
export const TOURNAMENT_STATUSES = [
  "draft",
  "registration_open",
  "registration_closed",
  "live",
  "awaiting_settlement",
  "settled",
  "cancelled",
] as const;
export const BEST_OF = ["1", "3"] as const;
export const MATCH_STATUSES = [
  "scheduled",
  "in_progress",
  "awaiting_scores",
  "disputed",
  "final",
  "forfeited",
  "bye",
] as const;
export const MATCH_SLOTS = ["a", "b"] as const;
export const CONSENSUS_STATES = [
  "awaiting_first",
  "awaiting_second",
  "agreed",
  "disputed",
  "submitting",
  "accepted",
  "partial",
  "rejected",
] as const;
export const LUCRA_SUBMISSION_OUTCOMES = ["pending", "accepted", "partial", "rejected", "transport_error"] as const;
export const DONATION_PROVIDERS = ["stub", "stripe"] as const;
export const DONATION_STATUSES = ["pending", "succeeded", "refunded", "failed"] as const;
export const SPONSOR_TIERS = ["presenting", "court", "prize"] as const;
export const REWARD_KINDS = ["lucra_reward", "sponsor_item", "credit"] as const;
export const REWARD_STATUSES = ["projected", "awarded", "claimed"] as const;
export const WEBHOOK_PROVIDERS = ["lucra"] as const;
export const WEBHOOK_PROCESSING_STATES = ["received", "processed", "ignored", "failed"] as const;
export const ACTOR_KINDS = ["player", "organizer", "system", "lucra_webhook"] as const;

export type VerificationState = (typeof VERIFICATION_STATES)[number];
export type TeamStatus = (typeof TEAM_STATUSES)[number];
export type UserRole = (typeof USER_ROLES)[number];
export type TeamInviteStatus = (typeof TEAM_INVITE_STATUSES)[number];
export type TeamRole = (typeof TEAM_ROLES)[number];
export type TournamentFormat = (typeof TOURNAMENT_FORMATS)[number];
export type Division = (typeof DIVISIONS)[number];
export type PrizeKind = (typeof PRIZE_KINDS)[number];
export type TournamentStatus = (typeof TOURNAMENT_STATUSES)[number];
export type BestOf = (typeof BEST_OF)[number];
export type MatchStatus = (typeof MATCH_STATUSES)[number];
export type MatchSlot = (typeof MATCH_SLOTS)[number];
export type ConsensusState = (typeof CONSENSUS_STATES)[number];
export type LucraSubmissionOutcome = (typeof LUCRA_SUBMISSION_OUTCOMES)[number];
export type DonationProvider = (typeof DONATION_PROVIDERS)[number];
export type DonationStatus = (typeof DONATION_STATUSES)[number];
export type SponsorTier = (typeof SPONSOR_TIERS)[number];
export type RewardKind = (typeof REWARD_KINDS)[number];
export type RewardStatus = (typeof REWARD_STATUSES)[number];
export type WebhookProvider = (typeof WEBHOOK_PROVIDERS)[number];
export type WebhookProcessingState = (typeof WEBHOOK_PROCESSING_STATES)[number];
export type ActorKind = (typeof ACTOR_KINDS)[number];

// ---------------------------------------------------------------------------
// Column helpers
// ---------------------------------------------------------------------------

const id = () => text("id").primaryKey();
const epochMs = (name: string) => integer(name);
const cents = (name: string) => integer(name);
const bool = (name: string) => integer(name, { mode: "boolean" });

/** Text enum column. Pair with `enumCheck` in the table's extra config. */
function enumColumn<const T extends readonly [string, ...string[]]>(name: string, values: T) {
  return text(name, { enum: values });
}

/** `CHECK (col IN ('a','b'))` — portable to Postgres unchanged. */
function enumCheck(table: string, column: string, values: readonly string[]) {
  const list: SQL = sql.join(
    values.map((v) => sql.raw(`'${v}'`)),
    sql.raw(", "),
  );
  return check(`${table}_${column}_check`, sql`${sql.raw(column)} IN (${list})`);
}

// ---------------------------------------------------------------------------
// 6.1 Identity and teams
// ---------------------------------------------------------------------------

export const users = sqliteTable(
  "users",
  {
    id: id(),
    displayName: text("display_name").notNull(),
    phoneE164: text("phone_e164"),
    email: text("email"),
    avatarUrl: text("avatar_url"),
    /** Sideout's own role; `organizer` gates `/api/admin/*`. Lucra owns wallet identity. */
    role: enumColumn("role", USER_ROLES).notNull().default("player"),
    createdAt: epochMs("created_at").notNull(),
  },
  (t) => [uniqueIndex("users_phone_e164_unique").on(t.phoneE164), enumCheck("users", "role", USER_ROLES)],
);

/**
 * One-time sign-in codes for phone auth. Only the HMAC of the code is stored;
 * a row is consumed on success and abandoned after `MAX_AUTH_CODE_ATTEMPTS`.
 */
export const authCodes = sqliteTable(
  "auth_codes",
  {
    id: id(),
    phoneE164: text("phone_e164").notNull(),
    codeHash: text("code_hash").notNull(),
    attempts: integer("attempts").notNull().default(0),
    expiresAt: epochMs("expires_at").notNull(),
    consumedAt: epochMs("consumed_at"),
    createdAt: epochMs("created_at").notNull(),
  },
  (t) => [index("auth_codes_phone_idx").on(t.phoneE164, t.createdAt)],
);

export const lucraLinks = sqliteTable(
  "lucra_links",
  {
    id: id(),
    userId: text("user_id")
      .notNull()
      .references(() => users.id),
    lucraUserId: text("lucra_user_id"),
    /** Stable opaque id we mint and send to Lucra as metadata. Never email/phone. */
    externalId: text("external_id").notNull(),
    verificationState: enumColumn("verification_state", VERIFICATION_STATES).notNull(),
    linkedAt: epochMs("linked_at"),
    lastSyncedAt: epochMs("last_synced_at"),
  },
  (t) => [
    uniqueIndex("lucra_links_external_id_unique").on(t.externalId),
    uniqueIndex("lucra_links_user_id_unique").on(t.userId),
    enumCheck("lucra_links", "verification_state", VERIFICATION_STATES),
  ],
);

export const charities = sqliteTable("charities", {
  id: id(),
  name: text("name").notNull(),
  ein: text("ein"),
  missionShort: text("mission_short").notNull(),
  logoUrl: text("logo_url"),
  websiteUrl: text("website_url"),
});

export const tournaments = sqliteTable(
  "tournaments",
  {
    id: id(),
    slug: text("slug").notNull(),
    name: text("name").notNull(),
    subtitle: text("subtitle"),
    beneficiaryId: text("beneficiary_id")
      .notNull()
      .references(() => charities.id),
    venueName: text("venue_name").notNull(),
    venueCity: text("venue_city").notNull(),
    venueState: text("venue_state").notNull(),
    /**
     * IANA time zone of the venue. Not in spec §6.2; added so schedule times can be
     * shown in venue-local time for a travelling event without guessing from the
     * server clock.
     */
    venueTimezone: text("venue_timezone").notNull(),
    startsAt: epochMs("starts_at").notNull(),
    endsAt: epochMs("ends_at").notNull(),
    format: enumColumn("format", TOURNAMENT_FORMATS).notNull(),
    division: enumColumn("division", DIVISIONS).notNull(),
    maxTeams: integer("max_teams").notNull(),
    entryDonationCents: cents("entry_donation_cents").notNull(),
    fundraisingGoalCents: cents("fundraising_goal_cents").notNull(),
    currency: text("currency").notNull(),
    prizeKind: enumColumn("prize_kind", PRIZE_KINDS).notNull(),
    status: enumColumn("status", TOURNAMENT_STATUSES).notNull(),
    lucraMatchupId: text("lucra_matchup_id"),
    /** Namespaced, globally unique; what we put in `matchupMetadata.externalId`. */
    lucraExternalId: text("lucra_external_id").notNull(),
    lucraGameId: text("lucra_game_id").notNull(),
    // OPEN: (§17.5) how a locationId is modelled for a travelling outdoor venue is
    // unresolved. Nullable, left null, until Lucra clarifies.
    lucraLocationId: text("lucra_location_id"),
    /**
     * The pools-stage draw configuration (`DrawConfig` from `@/domain/draw`, as
     * JSON) that produced the current pools and bracket skeleton; null until a
     * draw exists. The bracket stage reads its advancement rule from here rather
     * than trusting the caller to resend the rule that sized the bracket.
     */
    drawConfigJson: text("draw_config_json"),
    /**
     * The frozen close preview (`StoredClosePreview` from `@/server/close`, as
     * JSON): the final standings and projected rewards the organizer confirmed,
     * their hash, and when and by whom. Written once by the close flow when
     * `live → awaiting_settlement`; null before that. Organizer-only: the public
     * projection (`PublicTournament`) omits it.
     */
    closePreviewJson: text("close_preview_json"),
    createdAt: epochMs("created_at").notNull(),
  },
  (t) => [
    uniqueIndex("tournaments_slug_unique").on(t.slug),
    uniqueIndex("tournaments_lucra_external_id_unique").on(t.lucraExternalId),
    index("tournaments_status_idx").on(t.status),
    enumCheck("tournaments", "format", TOURNAMENT_FORMATS),
    enumCheck("tournaments", "division", DIVISIONS),
    enumCheck("tournaments", "prize_kind", PRIZE_KINDS),
    enumCheck("tournaments", "status", TOURNAMENT_STATUSES),
    check("tournaments_max_teams_positive", sql`max_teams > 0`),
    check("tournaments_entry_donation_nonneg", sql`entry_donation_cents >= 0`),
    check("tournaments_goal_nonneg", sql`fundraising_goal_cents >= 0`),
    check("tournaments_ends_after_start", sql`ends_at >= starts_at`),
  ],
);

export const teams = sqliteTable(
  "teams",
  {
    id: id(),
    tournamentId: text("tournament_id")
      .notNull()
      .references(() => tournaments.id),
    name: text("name").notNull(),
    seed: integer("seed"),
    status: enumColumn("status", TEAM_STATUSES).notNull(),
    createdAt: epochMs("created_at").notNull(),
  },
  (t) => [
    index("teams_tournament_id_idx").on(t.tournamentId),
    uniqueIndex("teams_tournament_seed_unique").on(t.tournamentId, t.seed),
    enumCheck("teams", "status", TEAM_STATUSES),
  ],
);

/**
 * Exactly two members per team (spec §6.1). A row-count constraint is not
 * expressible as a column CHECK, so the rule lives in `@/domain/team`
 * (`assertTeamRoster`) and the seed invariant tests; the (team_id, user_id)
 * unique index and the role check cover the row-level half.
 */
export const teamMembers = sqliteTable(
  "team_members",
  {
    id: id(),
    teamId: text("team_id")
      .notNull()
      .references(() => teams.id),
    userId: text("user_id")
      .notNull()
      .references(() => users.id),
    role: enumColumn("role", TEAM_ROLES).notNull(),
  },
  (t) => [
    uniqueIndex("team_members_team_user_unique").on(t.teamId, t.userId),
    index("team_members_user_id_idx").on(t.userId),
    enumCheck("team_members", "role", TEAM_ROLES),
  ],
);

/**
 * A captain's invitation to a partner, by phone. Accepting it (`POST
 * /api/teams/:id/join`) creates the `team_members` row for the signed-in user
 * whose phone matches. One pending invite per team at a time.
 */
export const teamInvites = sqliteTable(
  "team_invites",
  {
    id: id(),
    teamId: text("team_id")
      .notNull()
      .references(() => teams.id),
    invitedByUserId: text("invited_by_user_id")
      .notNull()
      .references(() => users.id),
    phoneE164: text("phone_e164").notNull(),
    status: enumColumn("status", TEAM_INVITE_STATUSES).notNull(),
    acceptedByUserId: text("accepted_by_user_id").references(() => users.id),
    createdAt: epochMs("created_at").notNull(),
    respondedAt: epochMs("responded_at"),
  },
  (t) => [
    index("team_invites_team_id_idx").on(t.teamId),
    index("team_invites_phone_idx").on(t.phoneE164, t.status),
    enumCheck("team_invites", "status", TEAM_INVITE_STATUSES),
  ],
);

// ---------------------------------------------------------------------------
// 6.2 Events and play
// ---------------------------------------------------------------------------

export const pools = sqliteTable(
  "pools",
  {
    id: id(),
    tournamentId: text("tournament_id")
      .notNull()
      .references(() => tournaments.id),
    label: text("label").notNull(),
    courtLabel: text("court_label").notNull(),
  },
  (t) => [
    index("pools_tournament_id_idx").on(t.tournamentId),
    uniqueIndex("pools_tournament_label_unique").on(t.tournamentId, t.label),
  ],
);

export const poolTeams = sqliteTable(
  "pool_teams",
  {
    id: id(),
    poolId: text("pool_id")
      .notNull()
      .references(() => pools.id),
    teamId: text("team_id")
      .notNull()
      .references(() => teams.id),
  },
  (t) => [
    uniqueIndex("pool_teams_pool_team_unique").on(t.poolId, t.teamId),
    uniqueIndex("pool_teams_team_unique").on(t.teamId),
  ],
);

export const matches = sqliteTable(
  "matches",
  {
    id: id(),
    tournamentId: text("tournament_id")
      .notNull()
      .references(() => tournaments.id),
    poolId: text("pool_id").references(() => pools.id),
    round: integer("round").notNull(),
    bracketPosition: integer("bracket_position"),
    courtLabel: text("court_label"),
    teamAId: text("team_a_id").references(() => teams.id),
    teamBId: text("team_b_id").references(() => teams.id),
    bestOf: enumColumn("best_of", BEST_OF).notNull(),
    status: enumColumn("status", MATCH_STATUSES).notNull(),
    winnerTeamId: text("winner_team_id").references(() => teams.id),
    nextMatchId: text("next_match_id").references((): AnySQLiteColumn => matches.id),
    nextMatchSlot: enumColumn("next_match_slot", MATCH_SLOTS),
    scheduledAt: epochMs("scheduled_at"),
    startedAt: epochMs("started_at"),
    finalizedAt: epochMs("finalized_at"),
  },
  (t) => [
    index("matches_tournament_id_idx").on(t.tournamentId),
    index("matches_pool_id_idx").on(t.poolId),
    index("matches_status_idx").on(t.status),
    uniqueIndex("matches_bracket_position_unique").on(t.tournamentId, t.bracketPosition),
    enumCheck("matches", "best_of", BEST_OF),
    enumCheck("matches", "status", MATCH_STATUSES),
    check("matches_next_match_slot_check", sql`next_match_slot IS NULL OR next_match_slot IN ('a', 'b')`),
    check("matches_bye_shape", sql`status <> 'bye' OR team_b_id IS NULL`),
    check("matches_distinct_teams", sql`team_a_id IS NULL OR team_b_id IS NULL OR team_a_id <> team_b_id`),
  ],
);

/** Written only by the consensus state machine (and the seed). */
export const sets = sqliteTable(
  "sets",
  {
    id: id(),
    matchId: text("match_id")
      .notNull()
      .references(() => matches.id),
    setNumber: integer("set_number").notNull(),
    teamAPoints: integer("team_a_points").notNull(),
    teamBPoints: integer("team_b_points").notNull(),
    agreed: bool("agreed").notNull(),
  },
  (t) => [
    uniqueIndex("sets_match_set_number_unique").on(t.matchId, t.setNumber),
    check("sets_set_number_range", sql`set_number BETWEEN 1 AND 3`),
    check("sets_points_nonneg", sql`team_a_points >= 0 AND team_b_points >= 0`),
  ],
);

// ---------------------------------------------------------------------------
// 6.3 Score consensus
// ---------------------------------------------------------------------------

/** One row per submission attempt. Never updated, only superseded. */
export const scoreSubmissions = sqliteTable(
  "score_submissions",
  {
    id: id(),
    matchId: text("match_id")
      .notNull()
      .references(() => matches.id),
    submittedByUserId: text("submitted_by_user_id")
      .notNull()
      .references(() => users.id),
    /** Null for an organizer's resolution, which speaks for neither team (`resolved_by_user_id` names who). */
    submittedForTeamId: text("submitted_for_team_id").references(() => teams.id),
    payloadJson: text("payload_json").notNull(),
    /** sha256 of the canonicalized, match-oriented scoreline (`hashScoreline` in `@/domain/scoreline-hash`). */
    payloadHash: text("payload_hash").notNull(),
    createdAt: epochMs("created_at").notNull(),
    supersededById: text("superseded_by_id").references((): AnySQLiteColumn => scoreSubmissions.id),
  },
  (t) => [
    index("score_submissions_match_id_idx").on(t.matchId),
    index("score_submissions_team_idx").on(t.submittedForTeamId),
  ],
);

export const matchConsensus = sqliteTable(
  "match_consensus",
  {
    id: id(),
    matchId: text("match_id")
      .notNull()
      .references(() => matches.id),
    state: enumColumn("state", CONSENSUS_STATES).notNull(),
    agreedPayloadJson: text("agreed_payload_json"),
    agreedPayloadHash: text("agreed_payload_hash"),
    disputedReason: text("disputed_reason"),
    resolvedByUserId: text("resolved_by_user_id").references(() => users.id),
    // OPEN: (§17.4) Lucra may not accept a first-class idempotency key. This is our
    // own key, minted once on entering `agreed`, and reused for every Lucra attempt.
    idempotencyKey: text("idempotency_key"),
    updatedAt: epochMs("updated_at").notNull(),
  },
  (t) => [
    uniqueIndex("match_consensus_match_id_unique").on(t.matchId),
    uniqueIndex("match_consensus_idempotency_key_unique").on(t.idempotencyKey),
    index("match_consensus_state_idx").on(t.state),
    enumCheck("match_consensus", "state", CONSENSUS_STATES),
  ],
);

/** Full request and response persisted for every Lucra attempt. */
export const lucraScoreSubmissions = sqliteTable(
  "lucra_score_submissions",
  {
    id: id(),
    matchId: text("match_id")
      .notNull()
      .references(() => matches.id),
    tournamentId: text("tournament_id")
      .notNull()
      .references(() => tournaments.id),
    idempotencyKey: text("idempotency_key").notNull(),
    requestJson: text("request_json").notNull(),
    responseJson: text("response_json"),
    httpStatus: integer("http_status"),
    affectedMatchupIdsJson: text("affected_matchup_ids_json").notNull(),
    failedMatchupIdsJson: text("failed_matchup_ids_json").notNull(),
    outcome: enumColumn("outcome", LUCRA_SUBMISSION_OUTCOMES).notNull(),
    attempt: integer("attempt").notNull(),
    createdAt: epochMs("created_at").notNull(),
  },
  (t) => [
    index("lucra_score_submissions_match_id_idx").on(t.matchId),
    index("lucra_score_submissions_tournament_id_idx").on(t.tournamentId),
    uniqueIndex("lucra_score_submissions_key_attempt_unique").on(t.idempotencyKey, t.attempt),
    enumCheck("lucra_score_submissions", "outcome", LUCRA_SUBMISSION_OUTCOMES),
    check("lucra_score_submissions_attempt_positive", sql`attempt >= 1`),
  ],
);

// ---------------------------------------------------------------------------
// 6.4 Charity and sponsorship
// ---------------------------------------------------------------------------

// OPEN: (§17.8) whether a charitable-gaming regime applies on top of the
// skill-contest framework is unresolved. The fallback is structural: entry fees
// live here, prizes live in `sponsors`/`rewards`, nothing joins or sums across
// the two, and no copy implies legal clearance.
/** Charitable ledger. No foreign key to `rewards` or `sponsors` (spec §4.3). */
export const donations = sqliteTable(
  "donations",
  {
    id: id(),
    tournamentId: text("tournament_id")
      .notNull()
      .references(() => tournaments.id),
    teamId: text("team_id").references(() => teams.id),
    userId: text("user_id").references(() => users.id),
    amountCents: cents("amount_cents").notNull(),
    currency: text("currency").notNull(),
    provider: enumColumn("provider", DONATION_PROVIDERS).notNull(),
    providerRef: text("provider_ref").notNull(),
    status: enumColumn("status", DONATION_STATUSES).notNull(),
    createdAt: epochMs("created_at").notNull(),
  },
  (t) => [
    index("donations_tournament_id_idx").on(t.tournamentId),
    index("donations_status_idx").on(t.status),
    enumCheck("donations", "provider", DONATION_PROVIDERS),
    enumCheck("donations", "status", DONATION_STATUSES),
    check("donations_amount_positive", sql`amount_cents > 0`),
  ],
);

export const sponsors = sqliteTable(
  "sponsors",
  {
    id: id(),
    tournamentId: text("tournament_id")
      .notNull()
      .references(() => tournaments.id),
    name: text("name").notNull(),
    logoUrl: text("logo_url"),
    tier: enumColumn("tier", SPONSOR_TIERS).notNull(),
    prizeContributionCents: cents("prize_contribution_cents").notNull(),
    currency: text("currency").notNull(),
  },
  (t) => [
    index("sponsors_tournament_id_idx").on(t.tournamentId),
    enumCheck("sponsors", "tier", SPONSOR_TIERS),
    check("sponsors_contribution_nonneg", sql`prize_contribution_cents >= 0`),
  ],
);

/** Prize ledger. Sponsor-funded; never computed from donations. */
export const rewards = sqliteTable(
  "rewards",
  {
    id: id(),
    tournamentId: text("tournament_id")
      .notNull()
      .references(() => tournaments.id),
    teamId: text("team_id")
      .notNull()
      .references(() => teams.id),
    placement: integer("placement").notNull(),
    kind: enumColumn("kind", REWARD_KINDS).notNull(),
    amountCents: cents("amount_cents"),
    currency: text("currency"),
    description: text("description").notNull(),
    lucraRewardRef: text("lucra_reward_ref"),
    status: enumColumn("status", REWARD_STATUSES).notNull(),
  },
  (t) => [
    index("rewards_tournament_id_idx").on(t.tournamentId),
    index("rewards_team_id_idx").on(t.teamId),
    enumCheck("rewards", "kind", REWARD_KINDS),
    enumCheck("rewards", "status", REWARD_STATUSES),
    check("rewards_placement_positive", sql`placement >= 1`),
    check("rewards_amount_has_currency", sql`amount_cents IS NULL OR currency IS NOT NULL`),
  ],
);

// ---------------------------------------------------------------------------
// 6.5 Plumbing
// ---------------------------------------------------------------------------

export const webhookEvents = sqliteTable(
  "webhook_events",
  {
    id: id(),
    provider: enumColumn("provider", WEBHOOK_PROVIDERS).notNull(),
    eventType: text("event_type").notNull(),
    externalEventId: text("external_event_id").notNull(),
    signatureValid: bool("signature_valid").notNull(),
    rawBody: text("raw_body").notNull(),
    parsedJson: text("parsed_json"),
    processingState: enumColumn("processing_state", WEBHOOK_PROCESSING_STATES).notNull(),
    receivedAt: epochMs("received_at").notNull(),
    processedAt: epochMs("processed_at"),
  },
  (t) => [
    uniqueIndex("webhook_events_external_event_id_unique").on(t.externalEventId),
    index("webhook_events_processing_state_idx").on(t.processingState),
    enumCheck("webhook_events", "provider", WEBHOOK_PROVIDERS),
    enumCheck("webhook_events", "processing_state", WEBHOOK_PROCESSING_STATES),
  ],
);

export const auditLog = sqliteTable(
  "audit_log",
  {
    id: id(),
    actorUserId: text("actor_user_id").references(() => users.id),
    actorKind: enumColumn("actor_kind", ACTOR_KINDS).notNull(),
    action: text("action").notNull(),
    subjectType: text("subject_type").notNull(),
    subjectId: text("subject_id").notNull(),
    detailJson: text("detail_json"),
    createdAt: epochMs("created_at").notNull(),
  },
  (t) => [
    index("audit_log_subject_idx").on(t.subjectType, t.subjectId),
    index("audit_log_created_at_idx").on(t.createdAt),
    enumCheck("audit_log", "actor_kind", ACTOR_KINDS),
  ],
);

// ---------------------------------------------------------------------------
// Row types
// ---------------------------------------------------------------------------

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type AuthCode = typeof authCodes.$inferSelect;
export type NewAuthCode = typeof authCodes.$inferInsert;
export type TeamInvite = typeof teamInvites.$inferSelect;
export type NewTeamInvite = typeof teamInvites.$inferInsert;
export type LucraLink = typeof lucraLinks.$inferSelect;
export type NewLucraLink = typeof lucraLinks.$inferInsert;
export type Charity = typeof charities.$inferSelect;
export type NewCharity = typeof charities.$inferInsert;
export type Tournament = typeof tournaments.$inferSelect;
export type NewTournament = typeof tournaments.$inferInsert;
export type Team = typeof teams.$inferSelect;
export type NewTeam = typeof teams.$inferInsert;
export type TeamMember = typeof teamMembers.$inferSelect;
export type NewTeamMember = typeof teamMembers.$inferInsert;
export type Pool = typeof pools.$inferSelect;
export type NewPool = typeof pools.$inferInsert;
export type PoolTeam = typeof poolTeams.$inferSelect;
export type NewPoolTeam = typeof poolTeams.$inferInsert;
export type Match = typeof matches.$inferSelect;
export type NewMatch = typeof matches.$inferInsert;
export type SetRow = typeof sets.$inferSelect;
export type NewSetRow = typeof sets.$inferInsert;
export type ScoreSubmission = typeof scoreSubmissions.$inferSelect;
export type NewScoreSubmission = typeof scoreSubmissions.$inferInsert;
export type MatchConsensus = typeof matchConsensus.$inferSelect;
export type NewMatchConsensus = typeof matchConsensus.$inferInsert;
export type LucraScoreSubmission = typeof lucraScoreSubmissions.$inferSelect;
export type Donation = typeof donations.$inferSelect;
export type NewDonation = typeof donations.$inferInsert;
export type Sponsor = typeof sponsors.$inferSelect;
export type NewSponsor = typeof sponsors.$inferInsert;
export type Reward = typeof rewards.$inferSelect;
export type NewReward = typeof rewards.$inferInsert;
export type WebhookEvent = typeof webhookEvents.$inferSelect;
export type AuditLogEntry = typeof auditLog.$inferSelect;
export type NewAuditLogEntry = typeof auditLog.$inferInsert;
